version: "3.8"

services:
  postgres-order:
    image: postgres:15
    container_name: order-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: order_db
    ports:
      - "5436:5432"

  postgres-courier:
    image: postgres:15
    container_name: courier-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: courier_db
    ports:
      - "5437:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: local-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"