spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
